import type { Metadata } from "next";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import Navbar from "./(Component)/Navbar";
import Footer from "./(Component)/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"w-full h-full bg-[#d6cbba] text-[#0f1516] " + `antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
